library(plotly)
library(RColorBrewer)
set.seed(123)
library(ggplot2)
df <- read.table(file="C://Users//admin//Desktop//snp_num.txt", header=FALSE, sep="\t", stringsAsFactors=FALSE)
df <- data.frame(variation = df$V1,number=df$V2)
pdf("fff.pdf",8,6)
p <- ggplot(df, aes(x=factor(variation), y=number, fill=variation)) +theme_minimal()+ theme(legend.position="bottom")
p  + scale_fill_manual(values = colorRampPalette(brewer.pal(12, "Accent"))(13)) 
dev.off()